Metrics/LineLength:
  Enabled: False

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 13

# Offense count: 12
Style/AsciiComments:
  Enabled: false

# Offense count: 3
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
